Register
handholdingsolution/certificate-generator pull request #1
Opened 2020-12-04 20:28 UTC by codermuskanj

Register Page

2020-12-05 04:03 UTC, harshgoel05 requested changes
Please remove the `.eslintcache` file and add it in
.gitignore

2020-12-05 04:04 UTC, harshgoel05 commented on src/App.js
>      </div>
Don't just directly add the component over here. Use react routing

2020-12-05 04:07 UTC, harshgoel05 requested changes

2020-12-05 04:07 UTC, harshgoel05 commented on src/Components/Register.js
> +export class Register extends Component {
Use functional components instead of class components

2020-12-05 04:07 UTC, harshgoel05 commented on src/Components/Register.js
> +              style={{
Create a style sheet and don't use inline styling

2020-12-06 19:19 UTC, codermuskanj commented
![Screenshot from 2020-12-07 00-44-26](https://user-images.githubusercontent.com/60754388/101290044-080e4e00-3826-11eb-8ab1-0b193b77297c.png)
![Screenshot from 2020-12-07 00-45-16](https://user-images.githubusercontent.com/60754388/101290047-0c3a6b80-3826-11eb-8e0d-40e98421f378.png)

2020-12-07 01:31 UTC, merged